### ISSUE TITLE
Unable to install peewee-db-evolve

### ISSUE THREAD

**Issue by abdulwahid24** [keredson/peewee-db-evolve#29]
Hi, 

I tried to install `peewee-db-evolve` using pipenv but got the below mentioned error.

```
$ pipenv install peewee-db-evolve
Installing peewee-db-evolve...
Collecting peewee-db-evolve
  Using cached https://files.pythonhosted.org/packages/4d/33/93d95ac781f1095312063ab4225bfdb9d3bf3117c767119f5920ecdab9e6/peewee-db-evolve-0.6.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-4yh31hoj/peewee-db-evolve/setup.py", line 16, in <module>
        version=__import__('peeweedbevolve').__version__,
      File "/tmp/pip-install-4yh31hoj/peewee-db-evolve/peeweedbevolve.py", line 687, in <module>
        _add_model_hook()
      File "/tmp/pip-install-4yh31hoj/peewee-db-evolve/peeweedbevolve.py", line 650, in _add_model_hook
        init = pw.BaseModel.__init__
    AttributeError: module 'peewee' has no attribute 'BaseModel'
    colorama not installed
    
    ----------------------------------------

Error:  An error occurred while installing peewee-db-evolve!
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-4yh31hoj/peewee-db-evolve/

This is likely caused by a bug in peewee-db-evolve. Report this to its maintainers.

```
Please have a look.

**Comment by artyomLisovskij** [comment]
same

**Comment by keredson** [comment]
fixed
