### ISSUE TITLE
peewee-db-evolve not installing when building app on Heroku

### ISSUE THREAD

**Issue by kharissa** [keredson/peewee-db-evolve#41]
I'm encountering an issue in deploying my React/Flask app to Heroku. 

Peewee-db-evolve is failing to install because colorama and peewee are not installed (however they are). The app is able to build and deploy when removing `peewee-db-evolve==3.7.0` from requirements.txt file (however, obviously the database is unusable). 

Any suggestions on what to try?

This is part of my `migrate.py` file:
```
import peeweedbevolve
from models import *
from models.base_model import db

print("Running Migration")
if os.getenv('FLASK_ENV') == 'production':
    db.evolve(ignore_tables={'base_model'}, interactive=False)
else:
    db.evolve(ignore_tables={'base_model'})
print("Finish Migration")
``` 

This is part of the output to `git push heroku master` :

```
remote:        Collecting peewee==3.8.2 (from -r /tmp/build_ff4018adddc8f1ec6857713e401a4b00/requirements.txt (line 13))
remote:          Downloading https://files.pythonhosted.org/packages/3b/10/619604d488416fb99a2f8ae145ae94f3ebac2812dbd1d334b0785ce7de2e/peewee-3.8.2.tar.gz (816kB)
remote:        Collecting peewee-db-evolve==3.7.0 (from -r /tmp/build_ff4018adddc8f1ec6857713e401a4b00/requirements.txt (line 14))
remote:          Downloading https://files.pythonhosted.org/packages/13/83/8c6435b2befc7a52a50ba83ee292890b2ae2f027eeeddc310b5018acca9f/peewee-db-evolve-3.7.0.tar.gz
remote:            Complete output from command python setup.py egg_info:
remote:            colorama not installed
remote:            peewee or herman not installed
remote:            Traceback (most recent call last):
remote:              File "<string>", line 1, in <module>
remote:              File "/tmp/pip-build-g4e5i86s/peewee-db-evolve/setup.py", line 16, in <module>
remote:                version=__import__('peeweedbevolve').__version__,
remote:              File "/tmp/pip-build-g4e5i86s/peewee-db-evolve/peeweedbevolve.py", line 27, in <module>
remote:                PW3 = not hasattr(pw, 'Clause')
remote:            NameError: name 'pw' is not defined
remote:
remote:            ----------------------------------------
remote:        Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-g4e5i86s/peewee-db-evolve/
remote:  !     Push rejected, failed to compile Python app.
remote:
remote:  !     Push failed
```

**Comment by kharissa** [comment]
After looking through `peeweedbevolve.py`, I saw that the version listed had been updated to 3.7.3. I ran `pip install peewee-db-evolve==3.7.3` to specifically update the package. Ran `git push heroku master` and everything compiled correctly.

**Comment by keredson** [comment]
Awesome.  Thanks for using!
